package com._pearls.cms.common.exception;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,
    BAD_REQUEST,
    VALIDATION_FAILED,
    AUTHENTICATION_FAILED,
    UNVERIFIED_ACCOUNT,
    EMAIL_DELIVERY_FAILED,
    ACCESS_DENIED,
    INTERNAL_SERVER_ERROR
}
